- pipeline.id: logstash
  path.config: /usr/share/logstash/pipeline/logstash.conf
  pipeline.workers: 1
- pipeline.id: solar-metrices
  path.config: /usr/share/logstash/pipeline/solar-metrics.conf
  pipeline.workers: 3
