name: "solar-monitoring--{{ COMPANY_NAME_VAR }}--{{ CLIENT_ID_VAR }}--{{ INSTALLATION_ID_VAR }}"

processors:
  - add_host_metadata: ~

metricbeat.modules:
  - module: system
    period: 10s
    metricsets:
      - cpu
      - load
      - memory
      - network
      - process
      - process_summary
      - socket_summary
    process.include_top_n:
      by_cpu: 5 # include top 5 processes by CPU
      by_memory: 5 # include top 5 processes by memory
  - module: system
    period: 1m
    metricsets:
      - filesystem
      - fsstat
    processors:
      - drop_event.when.regexp:
          system.filesystem.mount_point: "^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)"
  - module: system
    period: 15m
    metricsets:
      - uptime
  - module: http
    metricsets:
      - json
    period: 1s
    hosts: ["localhost:8080"]
    namespace: "metrics"
    path: "/metrics"

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

setup:
  kibana:
    host: "{{ KIBANA_HOST_VAR }}"

output.logstash:
  hosts: ["{{ LOGSTASH_HOST_VAR }}"]
